export const gameSetting = {
  damageRange: 0.2,
  criticalHitRate: 0.4,
  targetKilledNumber: 3,
  sleepRate: 0.3,
  firstNeedLevelUpPoint: 20,
  potionPrice: 30,
  magicPotionPrice: 50,
  stageNumberIndex: 3,


  playerStatus: {
    name: "プレイヤー",
    hp: 150,
    maxPlayerHp:150,
    mp: 20,
    maxPlayerMp: 20,
    attack: 10,
    defence: 2,
    fireDamage: 50,
    nowLevel: 1,
    nowHaveMoney: 0,
    canFire: true,
    nowHaveExperiencePoint: 0, 
    nowHavePotion: 3, 
    nowHaveMagicPotion: 3,
    canUsePotion: true,
    canUseMagicPotion: true,
    canUseSleep: false,
    canUsePoison: false,
  },

  enemies:[
    {
      name: "スライム",
      hp: 50,
      attack: 5,
      defence: 1,
      money: 10,
      experiencePoint: 10,
      enemyStageNumber: 1,
    },
    {
      name: "フェアリー",
      hp: 60,
      attack: 7,
      defence: 2,
      money: 20,
      experiencePoint: 10,
      enemyStageNumber: 1,
    },
    {
      name: "ガーゴイル",
      hp: 80,
      attack: 10,
      defence: 2,
      money: 25,
      experiencePoint: 10,
      enemyStageNumber: 1,
    },

    {
      name: "スケルトン",
      hp: 100,
      attack: 12,
      defence: 3,
      money: 30,
      experiencePoint: 30,
      enemyStageNumber: 2,
    },
    {
      name: "ゴースト",
      hp: 50,
      attack: 10,
      defence: 10,
      money: 50,
      experiencePoint: 20,
      enemyStageNumber: 2,
    },
    {
      name: "ゴブリン",
      hp: 60,
      attack: 15,
      defence: 1,
      money: 10,
      experiencePoint: 20,
      enemyStageNumber: 2,
    },
    {
      name: "ドラゴン",
      hp: 150,
      attack: 20,
      defence: 5,
      money: 50,
      experiencePoint: 60,
      enemyStageNumber: 3,
    },
    {
      name: "ポセイドン",
      hp: 100,
      attack: 30,
      defence: 10,
      money: 50,
      experiencePoint: 20,
      enemyStageNumber: 3,
    },
    {
      name: "大蛇",
      hp: 300,
      attack: 10,
      defence: 1,
      money: 100,
      experiencePoint: 50,
      enemyStageNumber: 3,
    }
  ]
}